address: 127.0.0.1:5000
baseUri: /api/ur

tracing:
  enabled: true
  request: true
  resp: true
  azure:
    key: 2dc68248-e2e9-445c-9661-0bfdbac1da6d

auth:
  keys:
  - abcd1234

keycloak:
  service: hazzys
  url: https://sso.sit-k8s.esquel.cn/
  realm: rfid
  roles:
  - hazzys

queries:
  items:
  - uri: /order/:id
    query:
      preset:
        code: B3

      sql: |
        SELECT uo.created_at as createdAt, ut.`type` ,ut.brand ,ut.company, utv.code , utv.`size` , utv.`type` , utv.mark_count as count
        from ur_orders uo join ur_tags ut on uo.id =ut.order_id JOIN ur_tag_vos utv on ut.id = utv.tag_id   
        where uo.id =? and utv.code = ? order by utv.code 
      params:
      - id
      - code

  - uri: /scan/:epc
    query:
      sql: |
        select bci .`style` , color ,`size` ,upc ,qr_code as qrCode
        from belle_carton_items bci 
        where bci .epc = ?
      params:
      - epc

  - uri: /batchQuery
    query:
      sql: |
        select epc, bci .`style` , color ,`size` ,upc ,qr_code as qrCode
        from belle_carton_items bci 
        where bci .epc in(?)
      params:
      - epc


cors:
  enabled: true
  allowAllOrigins: true


prometheus:
  enabled: true
  
database:
  connection: root:abcd1234@tcp(127.0.0.1)/belle?charset=utf8mb4&parseTime=True&loc=Local
  maxLifetime: 5m
  max: 100
  idel: 3

  initDB: true